Add variable for ETS & sectoral CO2 emissions
netzero2040/netzero2040 pull request #21
Opened 2023-02-07 08:38 UTC by danielhuppmann

This PR implements one aspect of #18: CO2 emissions by ETS/non-ETS and at the sectoral level.

cc @ClaKet

Two questions:
- We could add an additional hierarchy-level like `Emissions|CO2|{Sector}|{Final Energy Carrier}
- We could add an additional variable `Gross Emissions|CO2` (and subcategories) to clearly differentiate between the amount of CO2 released to the atmosphere versus CO2 captured in a sector, see this usage in the openentrance project [here](https://github.com/openENTRANCE/openentrance/blob/2e8e348d0903bc19257eeacd639dd0cb881c98bc/definitions/variable/emissions/emissions.yaml#L448)

Of course, both additions could be implemented later...

2023-02-10 18:02 UTC, zwiebo requested changes
TIMES needs additional emission categories
for CH4 and N2O

2023-02-10 18:02 UTC, zwiebo commented on definitions/variable/emissions.yaml
> +    unit: Mt CO2/yr
Times also accounts for emissions:
we should also include them
- Emission Source:
   - CO2:
        description: Carbon dioxide
   - CH4:
        description: Methane emissions
   - N2O:
        description: Nitrous oxide

2023-02-13 11:30 UTC, sebwehrle approved these changes

2023-02-13 11:36 UTC, danielhuppmann commented on definitions/variable/emissions.yaml
> +    unit: Mt CO2/yr
Thanks, added these emissions species

2023-02-13 11:38 UTC, danielhuppmann commented
Will merge and we can add more detailed CO2 emissions variables and "gross emissions" (for reporting emissions captured and requested/used at the source) later.

2023-02-13 11:38 UTC, merged