Update emission definitions
netzero2040/netzero2040 pull request #27
Opened 2023-04-14 09:28 UTC by zwiebo

Add a product based variable for the emission (Products are "Heat" and "Electricity")
Also introduced a new tag "Emission Kind" for the three Kinds of Emissions we are tracking.

2023-04-21 05:58 UTC, danielhuppmann requested changes
Thanks, see my comments inline.

After implementing my suggestions, please also reorder the list of variables to go from generic to specific...

2023-04-21 05:58 UTC, danielhuppmann commented on definitions/variable/tag_emission_kind.yaml
> +- Emission Kind:
Species is a more common name for different types of emissions or greenhouse gases...
```suggestion
- Emission Species:
```

2023-04-21 05:58 UTC, danielhuppmann commented on definitions/variable/emissions.yaml
> +- Emissions|Emission Kind:
```suggestion
- Emissions|{Emission Kind}:
```

2023-04-21 05:58 UTC, danielhuppmann commented on definitions/variable/emissions.yaml
> +    unit: kt
```suggestion
    unit: {Emission Kind}
```

2023-04-21 05:58 UTC, danielhuppmann commented on definitions/variable/tag_emission_kind.yaml
> +        description: Carbon dioxide
please add the "unit" as an attribute here to keep the emission species in the unit

2023-04-21 05:58 UTC, danielhuppmann commented on definitions/variable/emissions.yaml
> +- Emissions|Emission Kind|{Sector}:
```suggestion
- Emissions|{Emission Kind}|{Sector}:
```

2023-04-21 05:58 UTC, danielhuppmann commented on definitions/variable/emissions.yaml
> +    description:  emissions emitted electricity generation {Emission Kind}
```suggestion
    description: Emissions of {Emission Kind} emitted from electricity generation
```

2023-04-21 05:58 UTC, danielhuppmann commented on definitions/variable/emissions.yaml
> +    description: emissions emitted heat generation {Emission Kind}
```suggestion
    description: Emissions of {Emission Kind} emitted from heat generation 
```

2023-04-21 05:58 UTC, danielhuppmann commented on definitions/variable/tag_emission_kind.yaml
> +        description: Nitrous oxide
Please add an empty line at the end of this file

2023-04-21 10:52 UTC, zwiebo commented on definitions/variable/tag_emission_kind.yaml
> +        description: Nitrous oxide
```suggestion
        description: Nitrous oxide
        unit: Mt N2O/yr
```

2023-04-21 10:56 UTC, zwiebo reviewed
tried to implement your suggestions

2023-04-21 10:56 UTC, zwiebo commented on definitions/variable/tag_emission_kind.yaml
> +        description: Nitrous oxide
```suggestion
        description: Nitrous oxide
        unit: Mt/yr
```

2023-04-21 10:56 UTC, zwiebo commented on definitions/variable/tag_emission_kind.yaml
> +        description: Carbon dioxide
```suggestion
        description: Carbon dioxide
        unit: Mt/yr
```

2023-04-21 10:56 UTC, zwiebo commented on definitions/variable/tag_emission_kind.yaml
> +        description: Methane
```suggestion
        description: Methane
        unit: Mt/yr
```

2023-04-27 12:44 UTC, danielhuppmann approved these changes
Looks good, thanks!

2023-04-27 12:44 UTC, merged